
    create table audit_logs (
        created_at timestamp(6),
        entity_id bigint,
        id bigint generated by default as identity,
        tenant_id bigint,
        user_id bigint,
        action varchar(255) not null,
        details jsonb,
        entity_name varchar(255) not null,
        primary key (id)
    );

    create table branches (
        id bigint generated by default as identity,
        tenant_id bigint not null,
        address varchar(255),
        name varchar(255) not null,
        phone varchar(255),
        primary key (id)
    );

    create table cash_registers (
        closing_amount numeric(10,2),
        difference numeric(10,2),
        opening_amount numeric(10,2) not null,
        total_card numeric(10,2),
        total_cash numeric(10,2),
        total_sales numeric(10,2),
        total_transfer numeric(10,2),
        branch_id bigint not null,
        closed_at timestamp(6),
        closed_by_id bigint,
        id bigint generated by default as identity,
        opened_at timestamp(6),
        opened_by_id bigint not null,
        notes TEXT,
        status varchar(255) not null,
        primary key (id)
    );

    create table categories (
        id bigint generated by default as identity,
        tenant_id bigint not null,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table customers (
        id bigint generated by default as identity,
        tenant_id bigint not null,
        email varchar(255),
        name varchar(255) not null,
        nit varchar(255),
        phone varchar(255),
        primary key (id)
    );

    create table inventory (
        quantity integer default 0 not null,
        id bigint generated by default as identity,
        product_id bigint not null,
        warehouse_id bigint not null,
        primary key (id),
        unique (warehouse_id, product_id)
    );

    create table invoice_taxes (
        amount_calculated numeric(10,2) not null,
        applied_percentage numeric(5,2) not null,
        id bigint generated by default as identity,
        invoice_id bigint not null,
        tax_id bigint not null,
        primary key (id)
    );

    create table invoices (
        dte_type varchar(2),
        subtotal numeric(10,2) not null,
        tax numeric(10,2) not null,
        total numeric(10,2) not null,
        customer_id bigint,
        id bigint generated by default as identity,
        issued_at timestamp(6),
        order_id bigint not null unique,
        control_number varchar(31),
        generation_code varchar(36),
        reception_sello varchar(40),
        payment_method varchar(255) not null,
        primary key (id)
    );

    create table order_items (
        quantity integer not null,
        subtotal numeric(10,2) not null,
        unit_price numeric(10,2) not null,
        id bigint generated by default as identity,
        order_id bigint not null,
        product_id bigint not null,
        notes varchar(255),
        status varchar(255) not null,
        primary key (id)
    );

    create table orders (
        discount_value numeric(10,2),
        total numeric(10,2) not null,
        branch_id bigint not null,
        created_at timestamp(6),
        customer_id bigint,
        id bigint generated by default as identity,
        table_id bigint not null,
        updated_at timestamp(6),
        user_id bigint not null,
        discount_type varchar(255),
        status varchar(255) not null,
        primary key (id)
    );

    create table products (
        is_available boolean not null,
        min_stock integer default 0 not null,
        price numeric(10,2) not null,
        quantity integer default 0 not null,
        category_id bigint not null,
        id bigint generated by default as identity,
        tenant_id bigint not null,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table role_permissions (
        can_delete boolean not null,
        can_read boolean not null,
        can_write boolean not null,
        id bigint generated by default as identity,
        role_id bigint not null,
        component varchar(255) not null,
        primary key (id)
    );

    create table roles (
        id bigint generated by default as identity,
        tenant_id bigint not null,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    create table stock_movements (
        quantity integer not null,
        created_at timestamp(6) not null,
        created_by_id bigint,
        id bigint generated by default as identity,
        inventory_id bigint not null,
        movement_type varchar(255) not null check ((movement_type in ('IN','OUT','ADJUSTMENT'))),
        reason varchar(255),
        primary key (id)
    );

    create table tables (
        capacity integer not null,
        number integer not null,
        branch_id bigint not null,
        id bigint generated by default as identity,
        status varchar(255) not null,
        primary key (id)
    );

    create table taxes (
        is_active boolean not null,
        percentage numeric(5,2) not null,
        id bigint generated by default as identity,
        tenant_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table tenants (
        currency varchar(3) not null,
        is_active boolean not null,
        currency_symbol varchar(5) not null,
        created_at timestamp(6),
        id bigint generated by default as identity,
        nit varchar(30),
        nrc varchar(30),
        giro varchar(200),
        domain varchar(255) not null unique,
        name varchar(255) not null,
        primary key (id)
    );

    create table users (
        is_active boolean not null,
        branch_id bigint,
        id bigint generated by default as identity,
        role_id bigint not null,
        tenant_id bigint not null,
        username varchar(50) not null,
        name varchar(255) not null,
        password varchar(255) not null,
        primary key (id)
    );

    create table warehouses (
        is_default boolean not null,
        branch_id bigint not null,
        id bigint generated by default as identity,
        tenant_id bigint not null,
        description varchar(255),
        name varchar(255) not null,
        primary key (id)
    );

    alter table if exists audit_logs 
       add constraint FKqquet9030xtkk7jyvqwuy1byu 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists audit_logs 
       add constraint FKjs4iimve3y0xssbtve5ysyef0 
       foreign key (user_id) 
       references users;

    alter table if exists branches 
       add constraint FKs70s5ayvvphwrnsild64v5cna 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists cash_registers 
       add constraint FKbud4vq8hy9ae5mpoj9x4d6sr9 
       foreign key (branch_id) 
       references branches;

    alter table if exists cash_registers 
       add constraint FK7drq3l69q2al22onuxj7bkiyu 
       foreign key (closed_by_id) 
       references users;

    alter table if exists cash_registers 
       add constraint FKed7ptmqufwwk5sc4i0g3w83nx 
       foreign key (opened_by_id) 
       references users;

    alter table if exists categories 
       add constraint FKslnulryuuh7tq6tgyusgfk336 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists customers 
       add constraint FKpd6k5i4wnbhgk8fwug35v2x5t 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists inventory 
       add constraint FKq2yge7ebtfuvwufr6lwfwqy9l 
       foreign key (product_id) 
       references products;

    alter table if exists inventory 
       add constraint FK52wtagl8u69w0vduys8nsyi0x 
       foreign key (warehouse_id) 
       references warehouses;

    alter table if exists invoice_taxes 
       add constraint FK927rwvh0sr78p8r0w66js22nq 
       foreign key (invoice_id) 
       references invoices;

    alter table if exists invoice_taxes 
       add constraint FK70hgc643gm8idub8dhnm77hjy 
       foreign key (tax_id) 
       references taxes;

    alter table if exists invoices 
       add constraint FKq2w4hmh6l9othnp6cepp0cfe2 
       foreign key (customer_id) 
       references customers;

    alter table if exists invoices 
       add constraint FK4ko3y00tkkk2ya3p6wnefjj2f 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKbioxgbv59vetrxe0ejfubep1w 
       foreign key (order_id) 
       references orders;

    alter table if exists order_items 
       add constraint FKocimc7dtr037rh4ls4l95nlfi 
       foreign key (product_id) 
       references products;

    alter table if exists orders 
       add constraint FKjcfql8n80mxan8of04c8sd8k2 
       foreign key (branch_id) 
       references branches;

    alter table if exists orders 
       add constraint FKpxtb8awmi0dk6smoh2vp1litg 
       foreign key (customer_id) 
       references customers;

    alter table if exists orders 
       add constraint FKrkhrp1dape261t3x3spj7l5ny 
       foreign key (table_id) 
       references tables;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;

    alter table if exists products 
       add constraint FKog2rp4qthbtt2lfyhfo32lsw9 
       foreign key (category_id) 
       references categories;

    alter table if exists products 
       add constraint FKn8rwil6da3e23e0g04r5cw0mf 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists roles 
       add constraint FKmvypqr2nolkxxru0qnbw8rh5m 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists stock_movements 
       add constraint FKimja8gio8nl33quglj548pvid 
       foreign key (created_by_id) 
       references users;

    alter table if exists stock_movements 
       add constraint FKqlsf4auk79etqngl1f6h0x0mh 
       foreign key (inventory_id) 
       references inventory;

    alter table if exists tables 
       add constraint FK7prv4m6uk23c256n0j4ypfj4y 
       foreign key (branch_id) 
       references branches;

    alter table if exists taxes 
       add constraint FK1lobd6c0fb4p5jghharllc0nw 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists users 
       add constraint FK9o70sp9ku40077y38fk4wieyk 
       foreign key (branch_id) 
       references branches;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;

    alter table if exists users 
       add constraint FK21hn1a5ja1tve7ae02fnn4cld 
       foreign key (tenant_id) 
       references tenants;

    alter table if exists warehouses 
       add constraint FKcyjuy4jv0nys4buvnm452bxmn 
       foreign key (branch_id) 
       references branches;

    alter table if exists warehouses 
       add constraint FKn4qn12pkyk7u3o462u7n7sf5n 
       foreign key (tenant_id) 
       references tenants;
